name: Gerar Executável DJ

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Atualizar pip
        run: |
          python -m pip install --upgrade pip

      - name: Instalar dependências
        run: |
          pip install essentia==2.1b6.dev184
          pip install pyinstaller

      - name: Gerar executável
        run: |
          pyinstaller --onefile --clean `
          --hidden-import=essentia `
          --hidden-import=essentia.standard `
          --collect-submodules=essentia `
          --collect-data=essentia `
          --name DJ_AutoRename_Macedo `
          dj_analyzer.py

      - name: Upload do executável
        uses: actions/upload-artifact@v4
        with:
          name: DJ_AutoRename_Macedo
          path: dist/DJ_AutoRename_Macedo.exe
