name: Build DJ Analyzer EXE

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Atualizar pip
        run: |
          python -m pip install --upgrade pip

      - name: Instalar dependências
        run: |
          pip install essentia==2.1b6.dev184
          pip install pyinstaller

      - name: Descobrir caminho do Essentia
        id: essentia_path
        run: |
          python -c "import essentia, os; print(os.path.dirname(essentia.__file__))" > essentia_path.txt
          set /p ESSENTIA_PATH=<essentia_path.txt
          echo ESSENTIA_PATH=%ESSENTIA_PATH%>>%GITHUB_ENV

      - name: Build EXE
        run: |
          pyinstaller dj_analyzer.py ^
            --name DJ_AutoRename_Macedo ^
            --onefile ^
            --clean ^
            --hidden-import=essentia ^
            --hidden-import=essentia.standard ^
            --add-data "%ESSENTIA_PATH%;essentia"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: DJ_AutoRename_Macedo
          path: dist/DJ_AutoRename_Macedo.exe
